**Unit 0 - Prerequists Intro to Numpy**

In [ ]:
import numpy as np
import sys

**The Basics**

In [ ]:
a = np.array([1, 2, 3], dtype='int64')
b = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]], dtype='float')


In [ ]:
print(a)
print(b)

In [ ]:
# Get Dimension:
a.ndim

In [ ]:
# Get Shape
b.shape

In [ ]:
# Get size & Type
a.nbytes

**Accesing / Changing Specific elements, rows, columns etc**

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

In [ ]:
# Get specific elements [r,c]
a[1, -2]

In [ ]:
# Get a specific rows:
a[0, : ] 

In [ ]:
# Get a specific columns
a[1, 2]

In [ ]:
# Getting [startIndex : EndIndex : StepIndex]
a[0 ,1:6:2 ]

In [ ]:
a[1,5] = 20
print(a)

a[:, 2] = 5
print(a)

In [ ]:
# 3-d sample
b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(b)

In [ ]:
#Get a specific elements:
b[:, 1, :]

**Initializing Different Types of Array:**

In [ ]:
#All 0s matrix:
np.zeros((2,3))

In [ ]:
#All 1s matrix:
np.ones((2,3))

In [ ]:
#Any other numbers:
np.full((2,2), 99)

In [ ]:
# Any other number(full_like):
np.full_like(a, 4)

In [ ]:
#Random decimal Numbers:
np.random.rand(3, 4)

In [ ]:
#Random Integer Value:
np.random.randint(1, 100, size=(3,3))

In [ ]:
# The Identity:
np.identity(5)

In [ ]:
# Reapeat the array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

In [ ]:
output = np.ones((5,5))
output

z = np.zeros((3,3))
z[1,1] = 9
z

output[1:4, 1:4] = z
print(output)

**Mathematics**

In [ ]:
a = np.array([1, 2, 3, 4])
print(a)

In [ ]:
a + 2

In [ ]:
a - 2

In [ ]:
a * 2

In [ ]:
a / 2

In [ ]:
b = np.array([1,0,1,0])
a + b

In [ ]:
a ** 2

In [ ]:
# Take the sin:
np.cos(a)

**Linear Algebra**

In [130]:
a = np.full((2,3), 1)
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


array([[6, 6],
       [6, 6]])

In [131]:
c = np.identity(3)
np.linalg.det(c)

1.0

**Statictics**

In [135]:
stats = np.array([[1,2,3], [4,5,6]])
np.min(stats)
np.max(stats)

6

### Re-ordering Arrays:

In [139]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


### 